version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: lookmovie3_user
      POSTGRES_PASSWORD: lookmovie3_password
      POSTGRES_DB: lookmovie3_db
    ports:
      - "5432:5432"
    working_dir: /var/lib/postgresql/data
    volumes:
      - Postgres:/var/lib/postgresql/data
    tty: true
    networks:
      - lookmovie3

volumes:
  Postgres:

networks:
  lookmovie3:


