package rules.cep;
dialect  "mvel"


import com.ftn.sbnz.service.Entities.Models.FilmGenre;
import com.ftn.sbnz.service.Entities.Events.FilmRating;
import java.util.UUID;


declare GenreRecommendation
    @role( event )
end

declare GenreRecommendation
    userid: UUID
    genre: FilmGenre
end

global FilmGenre genre;
global UUID userId;


rule "Print count of films with same genre"
agenda-group "cep_genre"
when
    accumulate(
        FilmRating(),
        $count : count()
    )
then
    System.out.println("Number of films with genre " + genre + ": " + $count);
end

rule "2 and more genre recommendations in last week"
agenda-group "cep_genre"
when
    Number(intValue > 1) from accumulate(
        GenreRecommendation()
        over window:time(7d), count()
    )
then
    System.out.println("User " + userId + " has received 2 or more genre recommendations in last week");
end