package rules.cep;
dialect  "mvel"


import com.ftn.sbnz.service.Entities.Models.FilmGenre;
import com.ftn.sbnz.service.Entities.Events.FilmRating;
import java.util.UUID;


declare GenreRecommendation
    @role( event )
end

declare GenreRecommendation
    userid: UUID
    recommendedGenre: String
end

global UUID userId;

rule "inserted genre"
salience -1
when
    $genre : Genre()
then
    delete($genre);
end


rule "2 and more genre recommendations in last week"
//agenda-group "cep_genre"
salience 10
when
    $genre : Genre()
    $userId : UUID() from userId
    Number(intValue > 1) from accumulate(
        GenreRecommendation(userid == $userId, recommendedGenre.equals($genre.getGenre())) over window:time(7d), count()
    )
then
    System.out.println("User " + userId + " has received 2 or more genre " + $genre.getGenre() + " recommendations in last week");
end

rule "print all genre recommendations"
//agenda-group "cep_genre"
salience 10
when
    $genreRec: GenreRecommendation()
then
    System.out.println("User " + $genreRec.userid + " has received genre recommendation: " + $genreRec.recommendedGenre);
end


