package rules.forward;


import com.ftn.sbnz.service.Entities.Events.FilmRating;
import com.ftn.sbnz.service.Entities.Models.User;
import com.ftn.sbnz.service.Entities.Models.Film;
import com.ftn.sbnz.service.Entities.Models.FilmGenre;
import java.util.UUID;

global User updatedUser;
global UUID userId;
global Film recommendedFilm;
global Film likedFilm;

rule "hello FilmRating"
when
    $filmRating : FilmRating(isDone == false)
then
    System.out.println("FilmRating inserted");
end

rule "5 star rating"
when
    $filmRating : FilmRating(rating == 5, $film : film, isDone == false)
    $user : User(id == userId)
then
    System.out.println("5 star rating for film " + $film.getName() + " by user " + $user.getUsername());
    modify($user) {
        getLikedFilms().add($film);
    }
    likedFilm = $film;
    modify($filmRating) {
        setIsDone(true);
    }
end

rule "film added to liked films"
when
    $user : User(id == userId, $likedFilms : likedFilms)
    $film : Film() from $likedFilms
then
    System.out.println("Film " + $film.getName() + " added to liked films by user " + $user.getUsername());
    modify($user) {
        getLikedGenres().add($film.getGenre());
    }
end


rule "genre added to liked genres"
when
    $user : User(id == userId, $likedGenres : likedGenres)
    $genre : FilmGenre() from $likedGenres
    $film : Film(genre == $genre,  id != likedFilm.getId())
then
    System.out.println("Genre " + $genre + " added to liked genres by user " + $user.getUsername());
    System.out.println("Recommended mmmmmmmmm: " + $film.getName());
    recommendedFilm = $film;
    updatedUser = $user;
    update(updatedUser);
    update(recommendedFilm);
end